### ISSUE TITLE
Allow newer version of dependencies

### ISSUE THREAD

**Issue by jamesobutler** [neuropacs/neuropacs-py-api#18]
The hard pinning of dependencies in setup.cfg is too restrictive and newer versions should be allowed.
https://github.com/neuropacs/neuropacs-py-api/blob/7ddf7dace1a1c6bd717127c6f4e46709a8bea97e/setup.py#L14-L22

See the difference of approaching `install_requires` of setup.cfg versus a requirements.txt file.
https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/

> `install_requires` is a [Setuptools](https://packaging.python.org/en/latest/key_projects/#setuptools) setup.py keyword that should be used to specify what a project minimally needs to run correctly.

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

For example I’m not able to receive latest version of `requests` which includes big fixes from some security CVEs.

**Comment by neuropacman** [comment]
Thank you for this feedback! I have fixed the issue.

**Comment by jamesobutler** [comment]
For future reference, this was addressed by https://github.com/neuropacs/neuropacs-py-api/commit/af0d580132308099f0761f0c7e4f8e32370b8d08.
